### ISSUE TITLE
Linux should use archive extensions consistent with formats

### ISSUE THREAD

**Issue by crummel** [dotnet/toolset#11]
For internal archives, [.zip is always used](https://github.com/dotnet/toolset/blob/c8899f8124b5de7a98efa7a175007a3300feb2a6/build/FileExtensions.props#L6) as the file extension.  However, the check for whether to use a zip-format or gzip-format is made based on the OS [here](https://github.com/dotnet/toolset/blob/5da89ff20d80f6dcf830ada854c61f167a72b1bf/build/package/Archive.targets#L20), so on Linux we can end up with archives named with `.zip` but actually being gzip-formatted.  This causes problems for consumers that check file extensions to determine how to extract a file, e.g. [core-sdk](https://github.com/dotnet/core-sdk/blob/69c7fe8fe86e0d54a098508832b21cf32c383ad5/build/Prepare.targets#L47).

We should produce archives that have consistent file extensions and formats.

cc @tannergooding

**Comment by tannergooding** [comment]
CC. @dotnet/dotnet-cli
