### ISSUE TITLE
Source-build patch removal for toolset

### ISSUE THREAD

**Issue by crummel** [dotnet/toolset#1178]
Source-build has some patches that we are currently applying to your repo.  This issue tracks removing the patches.  These patches can be found at https://github.com/dotnet/source-build/tree/release/3.0/patches/toolset.

Patches that have the responsibility "Repo" and the Disposition "Incorporate" are patches that we believe are valid source-build fixes that should be moved into your repo.  Please let us know if these don't seem like good patches.  Any changes with the responsibility "source-build" is something that we plan to keep going forward or integrate in another way - please also let us know if you think there may be problems with those patches.

Patch name | Type | Disposition | Responsibility | Notes
-- | -- | -- | -- | --
toolset/0001-Exclude-test-projects-from-source-build.patch | ProjRemoval | Incorporate | Repo |

**Comment by nguerrera** [comment]
Do we need this or will dotnet/arcade#3034 handle it?

**Comment by crummel** [comment]
No, that should take care of it.  We can close this, thanks!
