### ISSUE TITLE
Fix dependency uptake of VSTest

### ISSUE THREAD

**Issue by crummel** [dotnet/toolset#1256]
Toolset has a dependency on VSTest:
https://github.com/dotnet/toolset/blob/0e48e294ecd191ba6715a030f78c6940b0d481bf/src/redist/redist.csproj#L23

And a partial entry in eng/Version.Details.xml:
https://github.com/dotnet/toolset/blob/0e48e294ecd191ba6715a030f78c6940b0d481bf/eng/Version.Details.xml#L41

This should be updated to complete the entry in Version.Details.xml and a subscription created from VSTest to Toolset so that a full BAR manifest will include the required VSTest bits.

**Comment by livarcocc** [comment]
A similar issue should be filled in the vstest repo. They are the ones who need to setup the infra-structure to publish to bar. Once they confirm their side of changes are in place, then we can do so here.

**Comment by crummel** [comment]
VSTest issue is https://github.com/microsoft/vstest/issues/2063.

**Comment by livarcocc** [comment]
Subscriptions have been created and vstest is publishing to darc. Once example of an update is here: https://github.com/dotnet/toolset/pull/1433.
