### ISSUE TITLE
dotnet-install script failed to download from master

### ISSUE THREAD

**Issue by ooooolivia** [dotnet/toolset#4023]
## Steps to reproduce
```powershell.exe -ExecutionPolicy ByPass .\dotnet-install.ps1 -Channel master```

## Expected  behavior
download the newest dotnet from master channel

## Actual behavior
```@DrewScoggins
 
Member
DrewScoggins commented 36 minutes ago
[2020/01/09 21:41:06][INFO] dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-alpha.1/dotnet-sdk-5.0.100-alpha.1-win-x64.zip
[2020/01/09 21:41:08][INFO] dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-alpha.1/dotnet-sdk-5.0.100-alpha.1-win-x64.zip
[2020/01/09 21:41:08][INFO] dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-alpha.1/dotnet-dev-win-x64.5.0.100-alpha.1.zip
[2020/01/09 21:41:10][INFO] dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-alpha.1/dotnet-dev-win-x64.5.0.100-alpha.1.zip```

**Comment by ooooolivia** [comment]
@DrewScoggins  @livarcocc

**Comment by wli3** [comment]
@livarcocc the new build is just called `dotnet-sdk-5.0.100-alpha.1-win-x64`.

**Comment by DrewScoggins** [comment]
When you run the command that we posted does it correctly download and install dotnet? Because that is the operative thing here not what the name of the build is.

**Comment by wli3** [comment]
The "latest" files is wrong too https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/latest.version

It should have a suffix. And there is no such file https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-alpha.1/dotnet-sdk-5.0.100-alpha.1-win-x64.zip

**Comment by wli3** [comment]
So i think it is more on publishing to the wrong place. Especially since we just edit that code

**Comment by livarcocc** [comment]
This is likely happening because of my change to the versioning scheme of core-sdk. We knew there would be some tail to the change.

**Comment by livarcocc** [comment]
I believe I know why this happens. Working to figure out why.

**Comment by sebastienros** [comment]
Remarks:
- The current blob (https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/latest.version) outputs `5.0.100-alpha.1.20059.13` while maestro++ only shows `5.0.100-alpha.1.20059.1`
- These versions still don't work with dotnet-isntall:

```
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-alpha.1.20059.13/dotnet-sdk-5.0.100-alpha.1.20059.13-linux-x64.tar.gz
```

**Comment by DrewScoggins** [comment]
It should be working now. I think the problem is that this change hadn't triggered a new build. Once that happens it seems like things are working again.

**Comment by sebastienros** [comment]
Thanks, the installation now works
