### ISSUE TITLE
Remove ref folder from published toolset

### ISSUE THREAD

**Issue by livarcocc** [dotnet/toolset#8]
When the toolset is being published, there is a ref folder present there that should not be. We need to remove that folder.

**Comment by johnbeisner** [comment]
The 3.0.100-alpha1-009347 of the Toolset does not have this folder: http://dotnetcli.blob.core.windows.net/dotnet/Toolset/3.0.100-alpha1-009347/dotnet-toolset-internal-3.0.100-alpha1-009347.zip - it seems the problem has been solved by the ongoing work in the repo.
